// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using quranTranslationExtractor.Infrastructure;

#nullable disable

namespace quranTranslationExtractor.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("quranTranslationExtractor.Domain.Ayat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AyatIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuraIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Ayats");
                });

            modelBuilder.Entity("quranTranslationExtractor.Domain.Sura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuraIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalVerses")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Suras");
                });

            modelBuilder.Entity("quranTranslationExtractor.Domain.Tafsir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AyatIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SuraIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TafsirIndexInSura")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Tafsirs");
                });
#pragma warning restore 612, 618
        }
    }
}
